### ISSUE TITLE
fujifilm script overwrites existing ratings

### ISSUE THREAD

**Issue by anarcat** [darktable-org/lua-scripts#124]
I had a rather frustrating experience with the `contrib/fujifilm_ratings.lua` script. it seems that it will happily overwrite any rating previously stored for existing pictures when *re-importing* folders. since I'm lazy, I have a tendency of starting darktable with `darktable ~/Photos/2018` which reimports existing pictures, but also imports any pics that have not yet been imported. this used to be non-destructive: existing pictures would essentially be left alone, but now with the fujifilm script, ratings get reset to the ones set in the camera. that's all nice if all photos are rated in-camera, but this is actually pretty rare in my case.

it seems the culprit is here:

https://github.com/darktable-org/lua-scripts/blob/1cd9a34761a1d41bf45c0b5e79364291539d6efc/contrib/fujifilm_ratings.lua#L63

I wonder how we should check if the rating exist before overwriting... `types.dt_lua_image_t.rating` doesn't seem to state what the value is for unrated images... would it be zero?

for now I've disable the script, but I would love to fix this somehow.

**Comment by wpferguson** [comment]
Initial import rating is configurable by the user.  Default is one, but you can set it to anything from 0 - 5.

The lua api manual says that the post-import-image event should only fire for new images that are imported.  I'll write a test script and see if that's the case, or it's firing for images that are re-imported also.

**Comment by anarcat** [comment]
so there's effectively no difference between an image rated by the user and one rated by the import mechanism?

would it be possible to inspect the initial import rating from Lua? then I could use that as a comparison...

**Comment by wpferguson** [comment]
I don't really have a way to test the fujifilm script since I don't have a fuji.  If you could take some pictures of a wall or something (subject doesn't matter) and give them various ratings in the camera, then post them somewhere that I could download them, I will run a series of tests and see if I can recreate the problem.  I will also test and see if I can find a situation where the post-import-image event fires for a re-imported image.

**Comment by anarcat** [comment]
i'll see what i can do... i rarely use the rating feature on the camera, so right now i disabled it to keep my sanity, but i'll make sure to send some pics your way when i try ratings again!

thanks for the help!

**Comment by wpferguson** [comment]
You're welcome

**Comment by wilecoyote2015** [comment]
In particular, I noticed that ratings are reset to the ratings assigned in camera for images that are not present in the database, but have an xmp file where a rating is defined.
This affects the use case where I have copied/moved a folder containing images rated and edited in darktable to a new location. If the moved images are opened in darktable, the script resets the ratings to the fujifilm ratings.

**Comment by wpferguson** [comment]
If you use darktable to do the copy/move, then this shouldn't happen, since darktable will already know about the images, and thus not re-import them.

I don't really have a way to test the fujifilm script since I don't have a fuji. If you could take some pictures of a wall or something (subject doesn't matter) and give them various ratings in the camera, then post them somewhere that I could download them then I would have something to work with.

**Comment by anarcat** [comment]
here's a 3-star rated photography of my lens cover. :)

![DSCF9460](https://user-images.githubusercontent.com/796623/56475695-ce72ae80-6459-11e9-9b09-8834d23a515a.JPG)

**Comment by wpferguson** [comment]
I'm sorriy, I didn't specify.  I need the raw file to test with.

**Comment by anarcat** [comment]
[DSCF9495.RAF.gz](https://github.com/darktable-org/lua-scripts/files/3107552/DSCF9495.RAF.gz)

heh. here's another picture then.
