### ISSUE TITLE
Change/reset the path for enfuseAdvanced export dir

### ISSUE THREAD

**Issue by sesselastronaut** [darktable-org/lua-scripts#292]
Just installed the enfuseAdvanced plugin, however on the first start I set the base directory wrong, for some reason selected an image flying around in my Pictures folder, resulting in the following error output when I try to use it:
```
sh: 1: /home/olsen/Pictures/Screenshot from 2012.png: Permission denied
rm: cannot remove '/tmp/aligned_0000.tif': No such file or directory
rm: cannot remove '/tmp/aligned_0001.tif': No such file or directory
58.960741 LUA ERROR align_image_stack failed
```
I was not able to find out how to chance or reset the directory, any hint welcome!

**Comment by wpferguson** [comment]
Open the exporter and select "DRI or DFF image".  Under that is a drop down menu.  Select "Target file".  Halfway down you can specify the directory.

**Comment by sesselastronaut** [comment]
Thanks @wpferguson for that indication, however this doesn't change the directory where the stacking is happening which seems to be a temporary/work directory and thus keeps throwing the same error. But I found out this path is set in .config/darktable/darktablerc setting this to `lua/executable_paths/align_image_stack=/tmp/` still results in the same behaviour & error:
 ```
sh: 1: /tmp/: Permission denied
rm: cannot remove '/tmp/aligned_0000.tif': No such file or directory
rm: cannot remove '/tmp/aligned_0001.tif': No such file or directory
46.911736 LUA ERROR align_image_stack failed
```
removing the whole line from the darktablerc is no dress for succes either and throws this error:
```
Written aligned images to files with prefix "/tmp/aligned_"
sh: 1: /home/olsen: Permission denied
58.692992 LUA ERROR enfuse failed
```

**Comment by wpferguson** [comment]
What operating system are you using?  I'm assuming Linux, but it could be MacOS.  

Here's how to fix it...

> sh: 1: /tmp/: Permission denied

This is the result of trying to run /tmp/ as the align_image_stack program instead of (linux) /usr/bin/align_image_stack or (macos) /Applications/Hugin.app/Contents/MacOS/align_image_stack.

To fix it, start executable manager.  If you are on Linux, then select align_image_stack from the drop down and hit the clear button.  The next time you run enfuseAdvanced, it should just pick up the executable from your path.  If you are on MacOS, then click the folder and navigate to the align_image_stack executable and select it.

> rm: cannot remove '/tmp/aligned_0000.tif': No such file or directory
rm: cannot remove '/tmp/aligned_0001.tif': No such file or directory

This is the script trying to clean up after itself, but no files were created since align_image_stack didn't run.

Another thought if you are on MacOS.  align_image_stack could also be in /Applications/enfuse.app/Contents/MacOS/align_image_stack.

**Comment by sesselastronaut** [comment]
This is on linux and this

> To fix it, start executable manager. If you are on Linux, then select align_image_stack from the drop down and hit the clear button.

 fixed it, many thanks!
