### ISSUE TITLE
gettextExample.lua - add make file to create the .mo file

### ISSUE THREAD

**Issue by supertobi** [darktable-org/lua-scripts#57]
We should add a make file to create the .mo files for the translations. I would welcome any help here, as I have no clue about make files.

**Comment by boucman** [comment]
hmm... the lua script repo doesn't have a makefile yet, because it's scripts...

adding one might confuse users... maybe

moreover makefiles are confusing, i'd rather use cmake which isn't simple either... overall i'm not sure it's worth the trouble to run the single command that generates .mo

I could be convinced otherwise,though
