### ISSUE TITLE
kml_export - read global options and use it for ImageMagick

### ISSUE THREAD

**Issue by elman22** [darktable-org/lua-scripts#59]
Current implementation uses fixed size for ImageMagick conversion

> local concertCommand = "convert -size 438x438 "..exported_image.." -resize 438x438 +profile \"*\" "..exportDirectory.."/"..imageFoldername..filename..".jpg"

Could you read settings under export selected -> global options -> max size and use it as variable for ImageMagick?

**Comment by elman22** [comment]
I was just thinking that actually there might not be a need to call ImageMagick twice. First conversion is fine - you create thumbnail. But instead of second conversion you could simply use image that was exported by darktable itself. And this image will have format and resolution you specify in export selected -> global options -> max size.

**Comment by supertobi** [comment]
Patches are welcome. Lua is not that hard. ;)

**Comment by elman22** [comment]
OK, here is my patched version. I did these changes:
- Fixed issue with exporting ARW (or any other than JPG format). Simply I strip extension instead of changing it into suffix separated by underscore.
- Removed second call to ImageMagick and I use image generated by darktable. This means that  user can choose image format, size and quality. Tested with jpg and png.Tiff is not working because GoogleEarth will not display it.
- Fixed bug with invalid XML when & was used in image.title or description. & is now encoded.
- Changed baloon style to be more user friendly and now it displays title and description.

[kml_export-elman.zip](https://github.com/darktable-org/lua-scripts/files/232436/kml_export-elman.zip)

**Comment by supertobi** [comment]
Coll thanks for the changes. I'm not at home at the moment and don't have a Linux PC here for testing. But if you could make a git pull request instead of adding a ZIP file here it would make the review process much easier. 

> Removed second call to ImageMagick and I use image generated by darktable. This means that user can choose image format, size and quality. Tested with jpg and png.Tiff is not working because GoogleEarth will not display it.

I think we should then add a warning, if something else then PNG or JPEG is selected. 

> Fixed bug with invalid XML when & was used in image.title or description. & is now encoded.

You should move this into function like the stripAccents( str ) function. I think we have to escape other characters, like < and >, too.

https://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents

**Comment by elman22** [comment]
OK, I have forked the repo and will make pull request when I implement your comments.
